---
abstract: 'check for spelling errors in POD files'
author:
  - ', Ivan Tubert-Brohman, All Rights Reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Spelling
no_index:
  directory:
    - inc
    - t
requires:
  Pod::Spell: 1.01
  perl: 5.6.0
resources:
  homepage: http://github.com/sartak/test-spelling/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/sartak/test-spelling.git
    web: http://github.com/sartak/test-spelling/tree
version: 0.15
